name: Ng2React CI CD

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Harbor
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.HARBOR_REGISTRY }}
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}

      - name: Build & Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.HARBOR_REGISTRY }}/ng2react/ng2react-ui:${{ github.sha }}

      - name: Checkout infra-manifests repo
        uses: actions/checkout@v4
        with:
          repository: dong7314/infra-manifests
          token: ${{ secrets.GH_TOKEN }}
          path: infra

      - name: Update image tag in deployment.yaml
        shell: powershell
        run: |
          $file = "infra/frontend/ng2react/deployment.yaml"
          $image = "${{ secrets.HARBOR_REGISTRY }}/ng2react/ng2react-ui:${{ github.sha }}"

          (Get-Content $file) -replace 'image:.*ng2react.*', "image: $image" | Set-Content $file

          Write-Host "--- Updated File Content Check ---"
          Get-Content $file | Select-String "image:"

      - name: Commit & Push infra-manifests
        shell: powershell
        run: |
          cd infra
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add frontend/ng2react/deployment.yaml
          git commit -m "[fe-deploy]: ng2react ${{ github.sha }}"
          git push

      - name: Docker cleanup
        if: always()
        shell: powershell
        run: |
          docker image prune -af
          docker builder prune -af
